In [6]:
import tensorflow as tf

In [2]:
matrix1 = tf.constant([[1, 3, 5, 7],
               [9, 11, 13 , 15],
               [17, 19, 21, 23],
               [25, 27, 29, 31]])
print(matrix1)

tf.Tensor(
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]], shape=(4, 4), dtype=int32)


In [3]:
matrixmax = tf.math.reduce_max(matrix1,axis=1)

print(matrixmax)

tf.Tensor([ 7 15 23 31], shape=(4,), dtype=int32)


In [4]:
vtr1 =  tf.constant([[2, 5, 1],
               [7, 12, 4],
               [19, 15, 6]])
vtr2 =  tf.constant([[13, 4, 11],
               [67, 23, 45],
               [71, 11, 10]])

vtr3 = vtr1 + vtr2

print(vtr3)

tf.Tensor(
[[15  9 12]
 [74 35 49]
 [90 26 16]], shape=(3, 3), dtype=int32)


In [5]:
vtr4 =  tf.constant([[12, 23],
               [34, 45],
               [56, 67]])
list1 = [[56, 12],[34, 15],[67, 87]]

vtr5 = vtr4 + list1 

print(vtr5)

tf.Tensor(
[[ 68  35]
 [ 68  60]
 [123 154]], shape=(3, 2), dtype=int32)
